### ISSUE TITLE
Add ReduceEdges operator

### ISSUE THREAD

**Issue by dcrankshaw** [amplab/graphx#12]
Add an operator that takes the set of edge triplets between two connected vertices and a reduce function that emits a single edge triplet. We need to decide how this will handle edges of opposite directions because a user should be able to reduce just the incoming edges, just the outgoing edges, or both(?).

**Comment by jegonzal** [comment]
Lets use the following semantics: 

``` scala
   def groupEdges[E2](f: Iter[EdgeTriplet[E,V]] => E2 ): Graph[V, E2]
```

where `f` is passed all the edges with the same src and dest pairs and returns a new edge attribute.  For example if the edge list is the following:

```
Src   |  Dst    |  E
0     |    1    |  0.1
1     |    0    |  0.2
1     |    0    |  0.3
0     |    1    |  0.5
```

Then a the following invocation:

``` scala
groupEdges( iter => iter.map(_.edge.data).sum ) 
```

produces a graph with the following:

```
Src   |  Dst    |  E
0     |    1    |  0.6
1     |    0    |  0.5
```

We should create a second function to collapsed the above edges into a single "undirected edge."

**Comment by dcrankshaw** [comment]
I added the initial code to do this in my repo (dcrankshaw/graphx). I actually added two methods (for primarily debugging reasons):

``` scala
   def groupEdges[E2](f: Iterator[Edge[E]] => E2 ): Graph[V, E2]
   def groupEdgeTriplets[E2](f: Iterator[EdgeTriplet[V,E]] => E2 ): Graph[V, E2]
```

We should discuss on Monday what the semantics of the second function to collapse opposing edges into a single edge should be. A few options I've thought of are:
- Duplicating the edge so we have two edges with the same edge data and opposite src, dst vertices
- Having one edge with an arbitrarily chosen direction. In this case we leave it up to the user to know that their edges are undirected.
- Allowing the user to specify the resulting edge direction (I can't think of any use case for this, but it subsumes the functionality of the previous one)
- Supporting an undirected edge type (or graph type) to allow users to more easily work with undirected or partially directed graphs. There are ML problems that work with partially directed graphs, aren't there?

Other thoughts on this?

**Comment by jegonzal** [comment]
Let's just do `groupEdges` and add `groupEdgeTriplets` later when it is needed.

**Comment by jegonzal** [comment]
Has this been resolved?

**Comment by dcrankshaw** [comment]
These have been implemented but right now they rely on an entire edge partition being able to fit in memory. That's probably okay for now.
