### ISSUE TITLE
Partition by Canonical Edge Direction 

### ISSUE THREAD

**Issue by jegonzal** [amplab/graphx#13]
To be able to efficiently collapse edges in reverse directions we need the edge partitioner to always place the edges (u,v) and (v,u) on the same machine.  The current edge partition logic is (defined in https://github.com/amplab/graphx/blob/master/graph/src/main/scala/org/apache/spark/graph/impl/GraphImpl.scala#L375):

``` scala
protected def edgePartitionFunction2D(src: Vid, dst: Vid, 
    numParts: Pid, ceilSqrtNumParts: Pid): Pid = {
    val mixingPrime: Vid = 1125899906842597L 
    val col: Pid = ((math.abs(src) * mixingPrime) % ceilSqrtNumParts).toInt
    val row: Pid = ((math.abs(dst) * mixingPrime) % ceilSqrtNumParts).toInt
    (col * ceilSqrtNumParts + row) % numParts
  }
```

For now I propose adding:

``` scala
protected def edgePartitionFunction2D(srcOrig: Vid, dstOrig: Vid, 
    numParts: Pid, ceilSqrtNumParts: Pid): Pid = {
    val mixingPrime: Vid = 1125899906842597L 
    val src = math.min(srcOrig, dstOrig)  // <-------- This line -------------
    val dst = math.max(srcOrig, dstOrig) // <-------- And this line -------
    val col: Pid = ((math.abs(src) * mixingPrime) % ceilSqrtNumParts).toInt
    val row: Pid = ((math.abs(dst) * mixingPrime) % ceilSqrtNumParts).toInt
    (col * ceilSqrtNumParts + row) % numParts
  }
```

**Comment by dcrankshaw** [comment]
I added this code in a new method called canonicalEdgePartitionFunction2D. I think we should evaluate how this affects load-balancing at some point though.

**Comment by jegonzal** [comment]
Agreed!  The 2D Partitioning can lead to terrible load balance on star
graphs.  We should definitely evaluate the implications.

**Comment by dcrankshaw** [comment]
We need to change the partitioner to be an upper triangular partitioning.

**Comment by jegonzal** [comment]
Has this been resolved?

**Comment by dcrankshaw** [comment]
Not yet. The naive fix of making sure that all the processors have an equal section of the upper triangular adjacency matrix is easy enough. But I think this still loses good load balancing properties because the sections won't be square anymore.

**Comment by dcrankshaw** [comment]
Fixed for now by doing a random vertex cut on canonical edges. This will have to be reconsidered if we go back to 2D partitioning.
