### ISSUE TITLE
Modifications to Aggregate Neighbors

### ISSUE THREAD

**Issue by jegonzal** [amplab/graphx#14]
Based on our discussion in the weekly meeting we want to make the following change to aggregate neighbors.  The current version is:

``` scala
def aggregateNeighbors[A: ClassManifest](
      mapFunc: (Vid, EdgeTriplet[VD, ED]) => Option[A],
      mergeFunc: (A, A) => A,
      direction: EdgeDirection)
    : Graph[(VD, Option[A]), ED]
```

It is worth noting that we actually did have the center vertex as an argument to the map function (addressing the primary issue).  Regardless, the proposed simplification is: 

``` scala
def aggregateNeighbors[A: ClassManifest](
      mapFunc: EdgeTriplet[VD, ED] => Iter[(Vid, A)],
      mergeFunc: (A, A) => A)
    : Graph[(VD, Option[A]), ED]
```

The new semantics of `mapFunc` is that it takes an edge triplet and then emits an iterator over "messages" to be sent to either of the vertices in the triplet (or even arbitrary vertices in the graph).  The `mergeFunc` is then applied to reduce the messages to a single message which is stored as the vertex attribute in the returned graph.

**Comment by ankurdave** [comment]
@jegonzal, do we still want this interface change after merging #23? I can port the change over if so.
