### ISSUE TITLE
how to install GraphX please some one help i need it very badly.

### ISSUE THREAD

**Issue by ghost** [amplab/graphx#142]
i set up hadoop cluster a long back.i can see all the folders that are given in amplab/graphx main page.but how to install graphx.what files need to be modified.please someone help please i need guidance very badly

**Comment by ankurdave** [comment]
GraphX has been merged into Apache Spark, so to install it you should follow the instructions for installing Spark: http://spark.apache.org/docs/latest/

GraphX will then be available by importing org.apache.spark.graphx._: http://spark.apache.org/docs/latest/graphx-programming-guide.html#getting-started
