### ISSUE TITLE
Wrong PageRank results

### ISSUE THREAD

**Issue by zma** [amplab/graphx#143]
Hi all,

I tried the static PageRank computation on GraphX (in Spark 1.0.0) with the following code:

```
import org.apache.spark._
import org.apache.spark.graphx._
import org.apache.spark.rdd.RDD

object ord extends Ordering[(VertexId, Double)] { def compare(a:(VertexId, Double), b:(VertexId, Double)) = a._2 compare b._2}

val graph = GraphLoader.edgeListFile(sc, "/lhome/zma/test.txt")
for (i <- 0 to 30) {
  println("iter: " + i)
  val ranks = graph.staticPageRank(i)
  ranks.vertices.top(100)(ord).foreach(println(_))
}
```

The `/lhome/zma/test.txt` contains a simple graph:

```
0 1
1 3
2 3
3 3
```

The PageRank implemenation (  https://github.com/amplab/graphx/blob/master/graphx/src/main/scala/org/apache/spark/graphx/lib/PageRank.scala ) uses this PageRank definition:

```
PR[i] = alpha + (1 - alpha) * inNbrs[i].map(j => oldPR[j] / outDeg[j]).sum
```

However, the results I get are:

```
iter: 0
(0,0.15)
(1,0.15)
(3,0.15)
(2,0.15)
iter: 1
(3,0.5325)
(1,0.27749999999999997)
(0,0.15)
(2,0.15)
iter: 2
(3,0.8384999999999999)
(1,0.27749999999999997)
(0,0.15)
(2,0.15)
iter: 3
(3,0.862725)
(1,0.27749999999999997)
(0,0.15)
(2,0.15)
...
```

The results with iterNum as 0 and 1 are correct. However, for "iter: 2":

The PageRank value for 3 should be:

```
0.15 + 0.85 * (0.27749999999999997 + 0.15 + 0.5325)
= 0.966
```

while the result is `(3,0.8384999999999999)`. It seems the PageRank of vertex 2 is not passed to the PageRank of vertex 3 (`0.8384999999999999 == 0.15 + 0.85 * (0.27749999999999997 + 0.5325)`).

I noticed that the Pregel implementation (https://github.com/amplab/graphx/blob/master/graphx/src/main/scala/org/apache/spark/graphx/Pregel.scala) only sends messages from vertices changed in last superstep. I can understand this performance optimization for less messages. However, is this PageRank implementation on top of this model wrong? Will passing the delta out from changed vertices be more suitable for implementation on this "Pregel" model in GraphX?

Please correct me if I am wrong at understanding some parts. I will appreciate it if additional information or pointers to them are provided.

**Comment by ankurdave** [comment]
I think you might be right, in which case the fix would be to change the `activeDirection` parameter to `EdgeDirection.Either` on lines 104 and 160 of PageRank.scala. This would cause messages to be sent _to_ updated vertices as well as from them.

@jegonzal what do you think?

**Comment by isjay** [comment]
I found the code in spark1.0 is correct. But not in the master branch.
    // Define the three functions needed to implement PageRank in the GraphX
    // version of Pregel
    def vertexProgram(id: VertexId, attr: Double, msgSum: Double): Double =
      resetProb + (1.0 - resetProb) \* msgSum
    def sendMessage(edge: EdgeTriplet[Double, Double]) =
      Iterator((edge.dstId, edge.srcAttr \* edge.attr))
    def messageCombiner(a: Double, b: Double): Double = a + b

**Comment by isjay** [comment]
graphx2 
forked from apache/spark 
Mirror of Apache Spark

Updated June 16, 2014 

graphx 
Former GraphX development repository. GraphX has been merged into Apache Spark; please submit pull requests there.

Updated April 23, 2014

**Comment by zma** [comment]
@JayinHuang Thanks for the comments. But could you be more specific?

"I found the code in spark1.0 is correct. But not in the master branch."

--> What do you means by spark1.0? Could you post a link to it? I check all branches from 3 repositories

https://github.com/apache/spark
https://github.com/amplab/graphx
https://github.com/amplab/graphx2

I am afraid there is no branch named "spark1.0".

"
// Define the three functions needed to implement PageRank in the GraphX
// version of Pregel
def vertexProgram(id: VertexId, attr: Double, msgSum: Double): Double =
resetProb + (1.0 - resetProb) \* msgSum
def sendMessage(edge: EdgeTriplet[Double, Double]) =
Iterator((edge.dstId, edge.srcAttr \* edge.attr))
def messageCombiner(a: Double, b: Double): Double = a + b
"

--> I check all 3 repositories and I am afraid the code you pasted above is the same as the PageRank.scala from those 3 repositories:

https://github.com/apache/spark/blob/master/graphx/src/main/scala/org/apache/spark/graphx/lib/PageRank.scala
https://github.com/amplab/graphx/blob/master/graphx/src/main/scala/org/apache/spark/graphx/lib/PageRank.scala
https://github.com/amplab/graphx2/blob/master/graphx/src/main/scala/org/apache/spark/graphx/lib/PageRank.scala

**Comment by zma** [comment]
@JayinHuang 

"
graphx2 
forked from apache/spark 
Mirror of Apache Spark

Updated June 16, 2014

graphx 
Former GraphX development repository. GraphX has been merged into Apache Spark; please submit pull requests there.

Updated April 23, 2014
"

Sorry that I do not fully understand this. Could you provide more details or a direct link?

**Comment by zma** [comment]
@ankurdave Thanks for the reply.

Using `EdgeDirection.Either` will make the Pregel work like this, if I understand correctly:
1. There are messgages on every edges initially.
2. Every vertex that is connected with otheres (in or out) will be activated and send messages since there are messgages on its in/out edges.

Hence, in each superstep, there is message on each edge.

If my understanding above is correct, the model with  `EdgeDirection.Either` should be alright for PageRank. It may run slower than the original implementation.

**Comment by jegonzal** [comment]
I have been looking into issues with the PageRank calculations and I have identified a bug which can be triggered with the following test:

https://github.com/apache/spark/pull/1228/files#diff-fa262e569c89e82b8bcfed5ef77e8307R98

In particular the `staticPageRank` when run on a graph of the following form:

```
(0) --> (1) --> (2) --> (3) <-- (4)
```

will incorrectly calculate the Pagerank of (3).  However, the default Graph.pagerank currently uses the delta page rank implementation which will calculate correct value for this test.  

However, there is currently a fix to PageRank as well as Pregel to address this issue here:

https://github.com/apache/spark/pull/1217

The main change is to allow vertex programs to run and send messages on every iteration (even if no message is received).  The proposed API for Pregel has the following form:

https://github.com/apache/spark/pull/1217/files#diff-e399679417ffa6eeedf26a7630baca16R226

``` scala
vertexProgram: (VertexId, VD, Option[A], VertexContext) => VD,
sendMsg: (EdgeTriplet[VD, ED], EdgeContext) => Iterator[(VertexId, A)],
mergeMsg: (A, A) => A)
```

The `vertexProgram` can deactivate the vertex by calling `context.deactive()` preventing it from sending messages in the current iteration.  A vertex is reactivated if it receives a message. 

Let us know what you think of the proposed change.

**Comment by zma** [comment]
@jegonzal Thanks for the updates with details!

The fix looks good to me. The improved Pregel implementation seems more "familiar" to me as I get to know the Pregel model by reading the Pregel paper.

I am closing this issue.
