### ISSUE TITLE
Getting eror to run scala testcases from https://github.com/amplab/graphx/blob/master/graphx/src/test/scala/org/apache/spark/graphx/GraphSuite.scala getting error 

### ISSUE THREAD

**Issue by Pallavim54** [amplab/graphx#144]
When i m trying to run scala testcases from https://github.com/amplab/graphx/blob/master/graphx/src/test/scala/org/apache/spark/graphx/GraphSuite.scala getting error 
## Stacktrace 

WARNING: -p has been deprecated and will be reused for a different (but still very cool) purpose in ScalaTest 2.0. Please change all uses of -p to -R. 
**\* RUN ABORTED **\* 
  java.lang.ClassNotFoundException: org.apache.spark.graphx.GraphTestSuite 
  at java.net.URLClassLoader$1.run(URLClassLoader.java:366) 
  at java.net.URLClassLoader$1.run(URLClassLoader.java:355) 
  at java.security.AccessController.doPrivileged(Native Method) 
  at java.net.URLClassLoader.findClass(URLClassLoader.java:354) 
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 
  at org.scalatest.tools.Runner$$anonfun$21.apply(Runner.scala:1470) 
  at org.scalatest.tools.Runner$$anonfun$21.apply(Runner.scala:1469) 
  at scala.collection.TraversableLike$$anonfun$filter$1.apply(TraversableLike.scala:264) 
  at scala.collection.immutable.List.foreach(List.scala:318) 
## In Scala Test IDE: 

Event: 
Run Aborted 

Message: 
Unable to load a Suite class. This could be due to an error in your runpath. Missing class: org.apache.spark.graphx.GraphTestSuite 
Date: 
Thu Jul 17 11:49:57 IST 2014 
Thread: 
Thread-2 
Exception: 
java.lang.ClassNotFoundException 
java.net.URLClassLoader$1.run(URLClassLoader.java:366) java.net.URLClassLoader$1.run(URLClassLoader.java:355) java.security.AccessController.doPrivileged(Native Method) java.net.URLClassLoader.findClass(URLClassLoader.java:354) java.lang.ClassLoader.loadClass(ClassLoader.java:424) java.lang.ClassLoader.loadClass(ClassLoader.java:357) org.scalatest.tools.Runner$$anonfun$21.apply(Runner.scala:1470) org.scalatest.tools.Runner$$anonfun$21.apply(Runner.scala:1469) scala.collection.TraversableLike$$anonfun$filter$1.apply(TraversableLike.scala:264) scala.collection.immutable.List.foreach(List.scala:318) scala.collection.TraversableLike$class.filter(TraversableLike.scala:263) scala.collection.AbstractTraversable.filter(Traversable.scala:105) org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1469) org.scalatest.tools.RunnerJFrame$RunnerThread$$anonfun$run$1.apply(RunnerJFrame.scala:1361) org.scalatest.tools.RunnerJFrame$RunnerThread$$anonfun$run$1.apply(RunnerJFrame.scala:1359) org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1645) org.scalatest.tools.RunnerJFrame$RunnerThread.run(RunnerJFrame.scala:1358) 

Can anyone please giude me .

**Comment by ankurdave** [comment]
Please use the repository at https://github.com/apache/spark, as GraphX has been merged into Spark and this repository is no longer maintained.

If the test failures persist, it may be a problem with your IDE. The standard way to run tests is from the command line using SBT:

```
~ $ git clone https://github.com/apache/spark
~ $ cd spark
~/spark $ sbt/sbt test
```

**Comment by ankurdave** [comment]
By the way, I'm not sure where "GraphTestSuite" is coming from -- if you want to run only GraphSuite, you can use:

```
~/spark $ sbt/sbt 'test-only org.apache.spark.graphx.GraphSuite'
```

**Comment by Pallavim54** [comment]
how to config sbt
