### ISSUE TITLE
Graph Constructor needs another type except VertexId?

### ISSUE THREAD

**Issue by johanstenberg92** [amplab/graphx#146]
Hi,

This might just be me making a fool about myself but I'm using GraphX to run a couple of distributed algorithms on rasters. I essentially just create a graph of the raster, then run a graph algorithm, then I convert it back. So I don't need any metadata except the VertexId (which denotes where in the raster the vertex is). However I can't be able to shake needing another type except the VertexId. I thought about using something like [(VertexId, Null)], and then using the null instance, but I'm guessing it's even cheaper with just a byte. However, is there any way to either skip this another type, or do you have a good reason for having it?

Thanks!

**Comment by ankurdave** [comment]
Unfortunately there isn't a way to skip the type. The best you can do is to use an Int, which is the smallest  type we specialize for.

**Comment by johanstenberg92** [comment]
Ok, thanks for the response!
