### ISSUE TITLE
Efficient storage of partition ids for each vertex. (the vid2pid map)

### ISSUE THREAD

**Issue by jegonzal** [amplab/graphx#31]
This is really two issues that may need to be solved simultaneously:
1. Storing Pids for each vertex in either an Array[Pid] or a BitSet
2. Storing the directionality of edges associated with each Pid.  This is needed to support single sided joins with the edge table.  

The second issue is slightly more pressing since in order to support the join optimization in `mapReduceTriplets` in which we only fill in the source or destination vertex attribute we need to know which partitions have in, out, or both edge directions for each vertex.

**Comment by jegonzal** [comment]
@ankurdave I reassigned this issue to you per our discussion today.

**Comment by jegonzal** [comment]
I have an idea!  What if instead of storing an Array[Pid] or a BitSet for every vertex we instead stored an Array[Vid] for every pid?  This actually has two major advantages.  First given that there are likely < 1000 PIDs the overhead of the arrays would be small and second we could then serialize the messages to other machines as a pair of arrays rather than a bunch of objects.  To do this I think we would want to add something like a `zipPartitions` function in the VertexSetRDD that would have the following signature:

``` scala
def zipPartitions[Z: ClassManifest](other: RDD[W])( f: PrimitiveKeyOpenHashMap[Vid, VD], Iterator[W] => Iterator[Z]): RDD[Z]
```

where `other` is assumed to have the same number of partitions as the VertexSetRDD and the function `f` is invoked passing in the `PrimitiveKeyOpenHashMap` and an iterator over the elements in the other RDD's partition.  @rxin does this seem like an appropriate use of the `PrimitiveKeyOpenHashMap`? It would be visible to a user facing function.

**Comment by ankurdave** [comment]
I don't understand how this would work. Could you elaborate?

Suppose we have `vTable: VertexSetRDD[VD]` and `vertexPlacement: RDD[(Pid, Array[Vid])]`, and we want `vTableReplicatedValues: RDD[(Pid, Array[VD])]`. Since these two RDDs don't share a partitioner, it seems we would need a broadcast join where each partition in `vTable` gets all elements of `vertexPlacement`. We could then populate many `PrimitiveKeyOpenHashMap[Vid, VD]`s, one per destination partition, then repartition and merge them to get the result.

**Comment by jegonzal** [comment]
Essentially I was thinking something like:

``` scala
// Making the pid2vid from a vid2pid (there is probably a more efficient way to make it)
val numParts = vTable.partitions.size
val pid2vid = vid2pid.mapPartitions { iter =>
  val pid2vid = new Array[ArrayBuffer[Vid]](numParts)
  for((vid,pids) <- iter) {
    pids.foreach { p => pid2vid(p).append(vid) } 
  }
 Iterator(pid2vid)
}
```

Then during broadcast we would do something like:

``` scala

// Implement an efficient serializer for
class VertexAttributeBlock[VD] (val vids: Array[Vid], val attr: Array[VD]);

val replicatedVertices = 
  pid2vid.zipPartitions(vTable.index.rdd, vTable.valuesRDD) { (pid2vidIter, indexIter, valuesIter) =>
    val pid2vid = pid2vidIter.next
    val index = indexIter.next
    val values = valuesIter.next
    // make a map
    val vmap = new PrimitiveKeyOpenHashMap(index, values)
    val output = new Array[(Pid, VertexAttributeBlock)](pid2vid.size)
    for( pid <- 0 until pid2vid.size ) {
      val block =  VertexAttributeBlock(pid2vid(pid), pid2vid(pid).map( vid => vmap(vid))
      output(pid) = (pid, block)
    } 
    output.iterator
  }.partitionBy(eTable.partitioner)
```

That said, if we were really smart we could probably ensure that vertices have the same canonical ordering in the `pid2vid` map as they do in the replicated indices thereby eliminating the need to store the vid array in the `VertexAttributeBlock`.

I hope that makes sense?  I apologize for bing a bit cryptic.

**Comment by jegonzal** [comment]
Actually, I thought a bit more about trying to avoid sending the vertex attributes and I think thats actually going to be pretty hard to do.
